# Generated by Django 4.2 on 2023-06-18 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='studentsData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('studentName', models.CharField(max_length=100)),
                ('fathersName', models.CharField(max_length=100)),
                ('mothersName', models.CharField(max_length=100)),
                ('dob', models.DateField()),
                ('gender', models.CharField(max_length=20)),
                ('identity', models.CharField(max_length=20)),
                ('indentityNum', models.IntegerField(default=0)),
                ('email', models.EmailField(max_length=200)),
                ('mobileNum', models.IntegerField()),
                ('password', models.CharField(max_length=20)),
            ],
        ),
    ]
