# Generated by Django 4.2 on 2023-06-18 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminApp', '0002_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='user',
        ),
    ]
