# Generated by Django 4.2 on 2023-06-26 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminApp', '0003_delete_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentsdata',
            name='image',
            field=models.ImageField(default='', upload_to='image'),
        ),
    ]
