# Generated by Django 4.2 on 2023-06-28 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminApp', '0004_studentsdata_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentsdata',
            name='studentSign',
            field=models.ImageField(default='default/d.jpg', upload_to='signature/image'),
        ),
        migrations.AlterField(
            model_name='studentsdata',
            name='image',
            field=models.ImageField(default='default/d.jpg', upload_to='profile/image'),
        ),
    ]
