# Generated by Django 4.2 on 2023-06-29 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminApp', '0005_studentsdata_studentsign_alter_studentsdata_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentsdata',
            name='course',
            field=models.CharField(default='', max_length=200),
        ),
    ]
