# Generated by Django 4.2 on 2023-07-03 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminApp', '0006_studentsdata_course'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=100)),
                ('students_opted', models.IntegerField(default=0)),
            ],
        ),
    ]
