# Generated by Django 4.2 on 2023-07-03 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminApp', '0007_course'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='students_opted',
        ),
    ]
