# Generated by Django 4.2 on 2023-07-07 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminApp', '0009_course_studentapplied'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='studentApplied',
            field=models.IntegerField(default='0'),
        ),
    ]
