# Generated by Django 4.2 on 2023-07-07 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminApp', '0013_alter_course_studentapplied'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='studentApplied',
        ),
        migrations.AddField(
            model_name='course',
            name='studentsApplied',
            field=models.IntegerField(default=0),
        ),
    ]
